### ISSUE TITLE
动捕数据

### ISSUE THREAD

**Issue by ChengBo5** [baojunshan/pose3d2bvh#1]
请问你这3DPOSE数据是自己生成的么，我用的单目摄像头做的3DPOSE数据很不稳，显示出来很晃。

**Comment by baojunshan** [comment]
> 请问你这3DPOSE数据是自己生成的么，我用的单目摄像头做的3DPOSE数据很不稳，显示出来很晃。

单目和多目确实会出现pose不稳定的现象，如果是非实时的，可以把数据整体做个平滑，比如savgol滤波；如果是实时的，可以利用前几帧做卡尔曼滤波的预测，这样可以略微减缓抖动现象。
